# -*- coding: utf-8 -*-
"""Calculadora_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoOzz5RdRjku9AAkblT41-8t2vwSh8Tz
"""

results = [0]
value1 = [0]
value2 = [0]
ope = [0]
op = ['*','/','+','-', '//', '%', '**']
num1 = ''; num2 = ''; sig = ''; resp = 'sim'

print("\nCALCULADORA")
if (resp == 'sim')or(resp == 'Sim')or(resp == 'SIM')or(resp == 's')or(resp =='S')or(resp =='Yes')or(resp =='yEs')or(resp =='yeS')or(resp =='YES')or(resp =='Y'):
  while (resp == 'sim')or(resp == 'Sim')or(resp == 'SIM')or(resp == 's')or(resp =='S')or(resp =='Yes')or(resp =='yEs')or(resp =='yeS')or(resp =='YES')or(resp =='Y'):
    print('\nDigite o primeiro numero:\n')
    num1 = input()
    #Verificacao da tentativa de insersao de valor nulo/Vazio (num1).
    if num1 == '':
      while num1 == '':
        print('\nErroZero. Valor nao reconhecido, tente novamente:\nDigite o primeiro numero:\n')
        num1 = input()
    #Verificacao da tentativa de insercao de valores Type String (num1).
    while type(num1) == str:
      try:
        num1 = int(num1)
      except ValueError:
        print('\nType Error. Valor nao reconhecido (',type(num1),'), tente novamente:\nDigite o primeiro numero:\n ')
        num1 = input()
      else:
        print()
    #Verificacao da operacao.
    print('Qual a operacao que deseja realizar? (* ; / ; + ; -) \n* = Multiplicacao \n/ = Divisao \n+ = Adicao \n- = Subtracao \n// = Divisao Inteira \n% = Resto da Divisao \n** = Potenciacao\n')
    sig = input()
    #Verificacao da validade da operacao.
    while (op.count(sig) == 0):
      print('\nA operacao nao pode ser devidamente realizada. Erro no termo. Tente outra operacao:\n')
      sig = input()
    #Continuidade
    print('\nDigite o segundo numero: \n')
    num2 = input()
    #Verificacao da tentativa de insersao de valor nulo/Vazio (num2).
    if num2 == '':
      while num2 == '':
        print('\nErroZero. Valor nao reconhecido, tente novamente:\nDigite o primeiro numero:\n')
        num2 = input()
    #Verificacao da tentativa de insercao de valores Type String (num2).
    while type(num2) == str:
      try:
        num2 = int(num2)
      except ValueError:
        print('\nType Error. Valor nao reconhecido (',type(num2),'), tente novamente:\nDigite o primeiro numero:\n ')
        num2 = input()
      else:
        print()
    #Confirmacao.
    print("\nA expressao em questao e",num1 , sig, num2,' correto?\n ')
    #Confirmacao do type (num1 e num2) e base de calculo.
    num1 = int(num1);num2 = int(num2)
    if (sig =="*"): calc =  num1 * num2
    elif(sig =="/"): calc = num1 / num2
    elif (sig == "+"): calc = num1 + num2
    elif (sig == "-"): calc = num1 - num2
    elif (sig == '//'): calc = num1 // num2
    elif (sig == '%'): calc = num1 % num2
    elif (sig == '**'): calc = num1 ** num2
    print('O resultado da expressao: ',num1 , sig, num2,' = ',calc,'\n')
    results.append(calc); value1.append(num1); value2.append(num2); ope.append(sig)
    print('Deseja realizar uma nova expressao? (Sim ou Nao)\n ')
    resp = input()

print('\nOperacao finalizada')
print('Foram realizadas', (int(len(results))-1),' operacao(oes), da(s) qual(ais) ')
for i, var in enumerate(results):
  if i == 0:
    print('\nINICIO')
  elif i > 0:
    print(value1[i],ope[i],value2[i],'=',results[i],'')

